### ISSUE TITLE
not found

### ISSUE THREAD

**Issue by michaelinipop** [linagora/linshare-dockerfile#1]
Hey guys I was working building this docker file and the  .war file was not found. Anyway this can get fixed ? 

http://download.linshare.org/versions/1.11/linshare-core-1.11.1-without-SSO.war

**Comment by fmartin-linagora** [comment]
Hi, sorry it's my mistake. I did not remove this old and deprecated repository. LinShare is now available through a docker-compose : https://github.com/linagora/linshare-docker.

All related docker containers are built from the following repositories : 
- https://github.com/linagora/linshare-frontend-dockerfile
- https://github.com/linagora/linshare-ui-admin-dockerfile
- https://github.com/linagora/linshare-ui-upload-request-dockerfile
- https://github.com/linagora/linshare-ui-user-dockerfile
- https://github.com/linagora/linshare-backend-dockerfile
- https://github.com/linagora/linshare-database-dockerfile

Hope it helps.

**Comment by fmartin-linagora** [comment]
May i close this issue ?
